#
# copy this file to your source root and execute: 'docker-compose -d -up jira'
# inside your terminal.
#
# our jira service container
#
jira:
  restart: 'always'
  # image: dunkelfrosch/jira:7.0.5
  build: .
  container_name: df-atls-jira

  ports:
    - "8080:8080"

  privileged: false
  stdin_open: true
  tty: true
